/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tiketpesawat;

import javax.swing.JOptionPane;

/**
 *
 * @author wesra
 */
public class formpesan extends javax.swing.JInternalFrame {

    /**
     * Creates new form formpesan
     */
    public formpesan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        namatxt = new javax.swing.JTextField();
        maskapaitxt = new javax.swing.JTextField();
        asalbox = new javax.swing.JComboBox<>();
        tujuanbox = new javax.swing.JComboBox<>();
        jenisbox = new javax.swing.JComboBox<>();
        tanggaltxt = new javax.swing.JTextField();
        hargatxt = new javax.swing.JTextField();
        jumlahtxt = new javax.swing.JTextField();
        hargatotaltxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pesananarea = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        hapusbtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("PT. TRAVELIN ");

        jLabel2.setText("Nama");

        jLabel3.setText("Nama Maskapai");

        jLabel4.setText("Tujuan");

        jLabel5.setText("Asal");

        jLabel6.setText("Jenis Tiket");

        jLabel7.setText("Tanggal Keberangkatan");

        jLabel8.setText("Harga");

        jLabel9.setText("Jumlah Tiket");

        jLabel10.setText("Total Harga");

        asalbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---PILIH---", "PADANG", "JAKARTA", "BANDUNG", "SURABAYA", "BALI", "MANADO", "JAYAPURA" }));
        asalbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asalboxActionPerformed(evt);
            }
        });

        tujuanbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---PILIH---", "PADANG", "JAKARTA", "BANDUNG", "SURABAYA", "BALI", "MANADO", "JAYAPURA" }));
        tujuanbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tujuanboxActionPerformed(evt);
            }
        });

        jenisbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---PILIH---", "EKONOMI", "BISNIS", "FIRST CLASS" }));

        hargatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargatxtActionPerformed(evt);
            }
        });

        hargatotaltxt.setEditable(false);
        hargatotaltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargatotaltxtActionPerformed(evt);
            }
        });

        jButton1.setText("PESAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        pesananarea.setEditable(false);
        pesananarea.setColumns(20);
        pesananarea.setRows(5);
        jScrollPane1.setViewportView(pesananarea);

        jButton2.setText("PROSES");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        hapusbtn.setText("HAPUS");
        hapusbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusbtnActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 8)); // NOI18N
        jLabel11.setText("isi harga tanpa menggunakan koma/titik");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9))
                                        .addGap(58, 58, 58)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(hargatotaltxt)
                                                .addComponent(hargatxt)
                                                .addComponent(tanggaltxt)
                                                .addComponent(jumlahtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jenisbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tujuanbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(asalbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(maskapaitxt, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(153, 153, 153)
                                .addComponent(namatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(260, 260, 260))))
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jButton2)
                        .addGap(38, 38, 38)
                        .addComponent(hapusbtn)
                        .addGap(32, 32, 32)
                        .addComponent(jButton1)
                        .addGap(45, 45, 45)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(maskapaitxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tanggaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(hargatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jumlahtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(asalbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tujuanbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jenisbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(hargatotaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(hapusbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hargatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargatxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (namatxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Isi nama terlebih dahulu");
        } else if(tanggaltxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Isi Nomor Handphone terlebih dahulu");
        }else if(maskapaitxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Isi Maskapai terlebih dahulu");
        }else if(hargatxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Isi Harga terlebih dahulu");
        }else if(hargatotaltxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Isi Harga terlebih dahulu");  
        }else if(jumlahtxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Isi Jumlah Tiket terlebih dahulu");
        }
        
        else{
            String tampil;
            tampil = "";
            tampil += "Nama Pemesan                     : "+ namatxt.getText()+"\n";
            tampil += "Tanggal                                    : "+ tanggaltxt.getText()+"\n";
            tampil += "Harga                                        : Rp. "+ hargatxt.getText()+"\n";
            tampil += "Jumlah Tiket                            : "+ jumlahtxt.getText()+"\n";
            tampil += "Maskapai Penerbangan        : "+ maskapaitxt.getText()+"\n";
            tampil += "Asal                                           : "+ asalbox.getSelectedItem()+"\n";
            tampil += "Tujuan                                        : "+ tujuanbox.getSelectedItem()+"\n";
            tampil += "Jenis Kelas                              : "+ jenisbox.getSelectedItem()+"\n";
            tampil += "Harga Total                              : Rp. "+ hargatotaltxt.getText()+"\n";
            
            pesananarea.setText("=============DETAIL PESANAN KAMAR==============\n"+tampil);
            
            JOptionPane.showMessageDialog(null,"Data berhasil disimpan");
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void asalboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asalboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asalboxActionPerformed

    private void tujuanboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tujuanboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tujuanboxActionPerformed

    private void hargatotaltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargatotaltxtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_hargatotaltxtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int harga = Integer.parseInt(hargatxt.getText());
        int jumlah = Integer.parseInt(jumlahtxt.getText());
        int total = harga * jumlah;
        hargatotaltxt.setText(String.valueOf(total));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void hapusbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusbtnActionPerformed
        // TODO add your handling code here:
        namatxt.setText("");
        hargatxt.setText("");
        hargatotaltxt.setText("");
        pesananarea.setText("");
        tanggaltxt.setText("");
        maskapaitxt.setText("");
        jumlahtxt.setText("");
        
    }//GEN-LAST:event_hapusbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> asalbox;
    private javax.swing.JButton hapusbtn;
    private javax.swing.JTextField hargatotaltxt;
    private javax.swing.JTextField hargatxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jenisbox;
    private javax.swing.JTextField jumlahtxt;
    private javax.swing.JTextField maskapaitxt;
    private javax.swing.JTextField namatxt;
    private javax.swing.JTextArea pesananarea;
    private javax.swing.JTextField tanggaltxt;
    private javax.swing.JComboBox<String> tujuanbox;
    // End of variables declaration//GEN-END:variables
}
